# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'exercise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseInstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_duration', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'exercise_instances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=150)),
                ('plan_description', models.TextField()),
                ('plan_difficulty', models.IntegerField()),
            ],
            options={
                'db_table': 'plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField()),
                ('day_name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'plan_days',
                'managed': False,
            },
        ),
    ]
